"""Per-request headers that only a platform's own page script can produce.

WeChat Channels shares are resolved through Tencent Yuanbao, whose API requires
signed headers (X-HY92/X-HY93/...) generated by Yuanbao's own page code. The
host agent opens a throwaway headless instance of the installed Chrome (fresh
temporary profile, never the operator's), injects the Cookies it just read from
the operator's Chrome, asks the page for its headers and closes it. Nothing is
kept between requests.
"""

from __future__ import annotations

import json
import tempfile
from collections.abc import Iterable
from http.cookiejar import Cookie
from typing import TYPE_CHECKING, cast

from app.services.site_sessions import HeaderPlugin, SiteSessionPolicy

if TYPE_CHECKING:
    from playwright._impl._api_structures import SetCookieParam

# Matches the Runner's WeChat Channels extractor so signatures and requests
# present one client identity.
PAGE_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
)
_PAGE_TIMEOUT_MS = 30_000

_YUANBAO_AUTH = """
async () => {
  if (location.origin !== 'https://yuanbao.tencent.com') return {};
  const auth = {
    userId: localStorage.getItem('yb_user_id') || '',
    token: localStorage.getItem('yb_token') || ''
  };
  let headers = {};
  if (window.$webApi?.getYbCommonHeaders) {
    headers = await window.$webApi.getYbCommonHeaders();
  }
  if (window.$webApi?.setContextualRequestHeaders) {
    const request = {url: '/api/weixin/get_parse_result', headers};
    await window.$webApi.setContextualRequestHeaders(request);
    headers = request.headers;
  }
  return {userId: auth.userId, token: auth.token, headers};
}
"""


class PageHeadersUnavailable(Exception):
    """The page did not produce a usable identity and header set."""


async def page_headers(
    policy: SiteSessionPolicy, cookies: tuple[Cookie, ...]
) -> bytes | None:
    """Return the sealed-to-be header payload, or None when the site needs none."""
    if policy.header_plugin is not HeaderPlugin.YUANBAO:
        return None
    from playwright.async_api import async_playwright

    with tempfile.TemporaryDirectory(prefix="framefetch-page-") as profile:
        async with async_playwright() as playwright:
            context = await playwright.chromium.launch_persistent_context(
                profile,
                channel="chrome",
                headless=True,
                user_agent=PAGE_USER_AGENT,
                # The page reports navigator.webdriver in X-webdriver; present
                # as the ordinary Chrome the operator uses.
                ignore_default_args=["--enable-automation"],
                args=["--disable-blink-features=AutomationControlled"],
            )
            try:
                await context.add_cookies(list(_playwright_cookies(cookies)))
                page = await context.new_page()
                await page.goto(
                    policy.keepalive_url,
                    wait_until="domcontentloaded",
                    timeout=_PAGE_TIMEOUT_MS,
                )
                await page.wait_for_function(
                    "() => !!window.$webApi", timeout=_PAGE_TIMEOUT_MS
                )
                auth = await page.evaluate(_YUANBAO_AUTH)
            finally:
                await context.close()
    return yuanbao_payload(auth, cookies)


def yuanbao_payload(auth: object, cookies: Iterable[Cookie]) -> bytes:
    """Identity from the page, else from the operator's login Cookies."""
    if not isinstance(auth, dict):
        raise PageHeadersUnavailable("page returned no identity")
    by_name = {cookie.name: cookie.value or "" for cookie in cookies}
    user = auth.get("userId") or by_name.get("hy_user")
    token = auth.get("token") or by_name.get("hy_token")
    headers = auth.get("headers")
    if not (isinstance(user, str) and user and isinstance(token, str) and token):
        raise PageHeadersUnavailable("no Yuanbao login identity")
    if not isinstance(headers, dict) or not headers:
        raise PageHeadersUnavailable("page produced no request headers")
    return json.dumps(
        {"userId": user, "token": token, "headers": headers},
        separators=(",", ":"),
    ).encode()


def _playwright_cookies(cookies: Iterable[Cookie]) -> Iterable[SetCookieParam]:
    for cookie in cookies:
        yield cast(
            "SetCookieParam",
            {
                "name": cookie.name,
                "value": cookie.value or "",
                "domain": cookie.domain,
                "path": cookie.path or "/",
                "expires": float(cookie.expires) if cookie.expires else -1,
                "secure": bool(cookie.secure),
                "httpOnly": cookie.has_nonstandard_attr("HttpOnly"),
                "sameSite": "Lax",
            },
        )
